CREATE TABLE `gesloc` (
  `idgesloc` int(8) unsigned NOT NULL auto_increment,
  `idpro` int(8) NOT NULL default '0',
  `idloc` int(8) NOT NULL default '0',
  `idges` int(8) NOT NULL default '0',
  `idbien` int(8) NOT NULL default '0',
  `agence` varchar(255) NOT NULL default '',
  `ref` varchar(255) NOT NULL default '',
  `prix` decimal(10,2) NOT NULL default '0.00',
  `charges` decimal(10,2) NOT NULL default '0.00',
  `indice` decimal(10,2) NOT NULL default '0.00',
  `assur` enum('0','1','2') NOT NULL default '0',
  `versepro` enum('0','1','2','3') NOT NULL default '0',
  `dt_sign` date,
  `dt_debu` date,
  `dt_fin` date,
  `dt_index` date,
  `dt_send` date,
  `dt_stop` date,
  `dt_entr` date,
  `rem` tinytext NOT NULL,
  `indexer` enum('0','1') NOT NULL default '1',
  `ref_bail` varchar(128) NOT NULL default '',
  `endebit` enum('0','1','2') default '0',
  `ref_etat` varchar(128) NOT NULL default '',
  `send_charges` enum('0','1') NOT NULL default '1',
  `dt_pay` date,
  `prix_debu` decimal(10,2) NOT NULL default '0.00',
  `charges_debu` decimal(10,2) NOT NULL default '0.00',
  `skip_charges` enum('0','1') NOT NULL default '0',
  PRIMARY KEY  (`idgesloc`),
  KEY `endebit` (`endebit`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
