CREATE TABLE `users` (
  `id_user` int(8) unsigned NOT NULL auto_increment,
  `id_lang` tinyint unsigned NOT NULL default 1,
  `id_civil` tinyint unsigned NOT NULL default 1,
  `id_eciv` tinyint unsigned NOT NULL default 1,
  `id_stat` tinyint unsigned NOT NULL default 2,
  `id_utype` tinyint unsigned NOT NULL default 1,
  `id_ref` varchar(16) NOT NULL default '',
  `pnom` varchar(64) NOT NULL default '',
  `nom` varchar(64) NOT NULL default '',
  `soc` varchar(64) NOT NULL default '',
  `street` varchar(128) NOT NULL default '',
  `num` varchar(16) NOT NULL default '',
  `cp` varchar(8) NOT NULL default '',
  `ville` varchar(48) NOT NULL default '',
  `id_cty` smallint(5) NOT NULL default 56,
  `datein` datetime NOT NULL,
  `datemod` datetime NOT NULL,
  `born` date NOT NULL,
  `wborn` varchar(64) NOT NULL,
  `natio` varchar(64) NOT NULL,
  `numnat` varchar(64) NOT NULL,
  `comment` text NOT NULL,
  PRIMARY KEY  (`id_user`),
  KEY `nom` (`nom`),
  KEY `id_status` (`id_status`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
